version: "3.8"

volumes:
    app_data:
        name: k9archiver_app_data
    static_files:
        name: k9archiver_static_files
    media_files:
        name: k9archiver_media_files

services:
    django:
        build:
            context: .
            dockerfile: Dockerfile
        image: archiver:production
        container_name: k9archiver_django_production
        command: /app/docker/start.sh server
        depends_on:
            - postgres
        env_file:
            - .env
        ports:
            - 8000:8000
        volumes:
            - static_files:/app/static
            - media_files:/app/media

    postgres:
        image: postgres:13.3-alpine
        container_name: k9archiver_postgres_production
        volumes:
            - app_data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: kpostgres
            POSTGRES_USER: kpostgres
            POSTGRES_DB: kpostgres
        # ports:
        #     - "5432:5432"
    
    
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        image: nginx:development
        container_name: k9archiver_nginx_production
        ports:
            - 80:80
        depends_on:
            - django
        volumes:
            - static_files:/app/static:ro
            - media_files:/app/media:ro